(source gnu)
(source melpa)
(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "diminish")
(depends-on "drag-stuff")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "init-loader")
(depends-on "let-alist")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "auto-install")
(depends-on "crosshairs")
(depends-on "tabbar")
(depends-on "yascroll")
(depends-on "anything")
(depends-on "auto-capitalize")
(depends-on "auto-complete")
(depends-on "company")
(depends-on "company-c-headers")
(depends-on "ctags")
(depends-on "eldoc")
(depends-on "flycheck-pos-tip")
;(depends-on "grammar")
(depends-on "highlight-indentation")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "anzu")
(depends-on "google-translate")
(depends-on "highlight-symbol")
(depends-on "migemo")
(depends-on "open-junk-file")
(depends-on "quickrun")
;(depends-on "sdic")
(depends-on "search-web")
(depends-on "codic")
(depends-on "eproject")
(depends-on "multi-term")
(depends-on "google-c-style")
(depends-on "perl-completion")
(depends-on "flycheck-pyflakes")
(depends-on "ruby-block")
(depends-on "php-mode")
(depends-on "gnuplot")
(depends-on "coffee-mode")
(depends-on "scss-mode")
(depends-on "rinari")
(depends-on "cmake-mode")
(depends-on "powerline")
(depends-on "ctags-update")
(depends-on "eldoc-extension")
(depends-on "c-eldoc")
(depends-on "ruby-electric")
(depends-on "slim-mode")
(depends-on "rhtml-mode")
(depends-on "cpputils-cmake")
(depends-on "anything-exuberant-ctags")
(depends-on "auto-complete-c-headers")
(depends-on "auto-complete-clang")
(depends-on "auto-complete-clang-async")
(depends-on "cmake-ide")
(depends-on "rtags")
(depends-on "robe")
(depends-on "enh-ruby-mode")
(depends-on "jedi")
(depends-on "omnisharp")
(depends-on "csharp-mode")
(depends-on "emacs-eclim")
(depends-on "flycheck-tip")

(depends-on "flycheck-color-mode-line" :git "https://github.com/flycheck/flycheck-color-mode-line.git")
(depends-on "ruby-refactor" :git "https://github.com/ajvargo/ruby-refactor")
(depends-on "textlint" :git "https://github.com/DamienCassou/textlint")

(depends-on "cmake-font-lock"
			:git "https://github.com/Lindydancer/cmake-font-lock"
			:files ("*.el" "bin"))

(depends-on "php-completion"
        :git "https://github.com/suzuki/php-completion.git"
        :branch "develop"
        :files ("*.el" "phpcmp-index-of-*"))
		
(depends-on "processing2-emacs"
			:git "https://github.com/ptrv/processing2-emacs"
			:files ("*.el" "snippets"))

;(depends-on "verilog-yas" :git "https://github.com/trairia/verilog-yas.git")
;(depends-on "yasnippet-coffee-script-snippets" :git "https://github.com/jarrelcobb/yasnippet-coffee-script-snippets.git")
;(depends-on "js-yasnippets" :git "https://github.com/azer/js-yasnippets.git")
